on: [push, pull_request]

name: Build Tools

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - netstorageserver
          - portfinder
          - updateserver
          - sign
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install deps
        run: sudo apt install llvm-dev libclang clang
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --manifest-path tools/${{ matrix.tool }}/Cargo.toml --release --target=${{ matrix.target }}
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.tool }}_${{ matrix.target }}
          path: tools/${{ matrix.tool }}/target/${{ matrix.target }}/release/${{ matrix.tool }}*
