on: [push, pull_request]

name: Build Tools

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolpath:
          - netstorageserver
          - portfinder
          - updateserver
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install deps
        run: sudo apt install llvm-dev libclang-dev clang
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --manifest-path tools/${{ matrix.toolpath }}/Cargo.toml --release --target=${{ matrix.target }} 