on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - netstorageserver
          - portfinder
          - sign
          - updateserver
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
        
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: curl https://sh.rustup.rs -sSf | sh -y
      - name: Build ${{ matrix.tool }}
        run: cargo b --manifest-path tools/${{ matrix.tool }}/Cargo.toml --release --target=${{ matrix.target }}
